name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv and set up Python
      uses: astral-sh/setup-uv@v5
        
    - name: Install the project
      run: |
        uv sync --locked --all-extras --dev
        
    - name: Run tests
      run: |
        uv run pytest
